sudo: required
language: node_js
node_js:
  - v10.15.3
cache:
  directories:
    - node_modules
notifications:
  email: false
# S: Build Lifecycle
before_install:
  - echo "before_install running..."
  - pwd
install:
  - echo "install running..."
  # - npm install
before_script:
  - echo "before_install running..."
script:
  - echo "script running..."
  # - npm run build
  - tar -cvf bunder.tar ./app/dist
after_success:
  - echo "after_success running..."
  # - node deploy.js
  - echo "压缩build 文件，上传到服务器"
after_failure:
  - echo "after_failure running..."
branches:
  only:
    - travis-test
env:
 global: